# Generated by Django 3.2.4 on 2021-06-22 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('New order', 'New order'), ('Waiting for payment', 'Waiting for payment'), ('Paid', 'Paid'), ('Preparing the order', 'Preparing the order'), ('Waiting for Waybill', 'Waiting for Waybill'), ('Waiting for the courier', 'Waiting for the courier'), ('Sent', 'Sent'), ('Cancel', 'Cancel')], default='New order', max_length=64)),
                ('product', models.ManyToManyField(to='shop_app.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
